### ISSUE TITLE
Installation de sensio insight

### ISSUE THREAD

**Issue by NicoLarson** [NicoLarson/Premier_Blog#11]
**Description:** Le but est vérifier la qualité du code
SP: 2

**Critère d'acceptance:**

- Obtenir au minimum une médaille d’argent
- Respect des PSR

**Tâche technique:**

- Analyser le projet dans github avec symfony insight
- Corriger les suggestions

**Annexes:**
https://insight.symfony.com/docs/github/analyze-a-symfony-project-on-github.html

**Comment by cacahouwete** [comment]
Done
